# Scaffolded by holocron setup — edit this file freely.
# Source:  theholocron/holocron · packages/cli/src/commands/setup.ts

codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  status:
    project:
      default:
        target: auto
        if_not_found: success
        threshold: 2%
    patch:
      default:
        target: 80%
        if_not_found: success

comment:
  layout: "reach,diff,flags,components"
  behavior: default
  require_changes: true

component_management:
  default_rules:
    statuses:
      - type: patch
        target: 80%
        if_not_found: success
  individual_components:
    []
